Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,25 +2,18 @@ name: dynamic-submission-web-v1
 
 on:
   push:
-    branches: [ test/ci_cd]
-  pull_request:
-    branches: [ test/ci_cd] 
+    tags:
+      - '*.*'
   workflow_dispatch:
     inputs:
       environment:
         type: choice
         description: Select Environment
         options:
-        - DEV
-        - QA
-        - UAT
-     
-  create:
-    tags:
-      - '*.*'
+          - DEV
+          - QA
+          - UAT
 
-
-     
 jobs:  
   build:
     name: Build and Deploy Angular Project
@@ -36,33 +29,34 @@ jobs:
       - name: Building project
         run: ng build
 
-      
-      - name: Deploy to DEV
-        if: ${{ github.event.inputs.environment == 'dev'}}
+      - name: Determine Environment
+        id: env
+        run: echo "::set-output name=env::${{ github.event.inputs.environment }}"
+
+      - name: Deploy
         run: |
-          Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
-          Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
-          # Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            ENV=${{ steps.env.outputs.env }}
+          else
+            # Extract environment from the tag name
+            ENV=$(echo "${{ github.ref }}" | cut -d '/' -f 3)
+          fi
 
-      - name: Deploy to QA
-        if: ${{ github.event.inputs.environment == 'QA'}}
-        run: |
-          Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
-          Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
-          Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
-
-      - name: Deploy to UAT
-        if: ${{ github.event.inputs.environment == 'UAT'}}
-        run: |
-          Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
-          Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
-          Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
-
-
-      # - name: Copying from dist to IIS folder
-      #   run: |      
-      #     Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
-      #     Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
-      #     Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
-
-      
+          if [ "$ENV" == "DEV" ]; then
+            # Deployment to DEV
+            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
+            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
+          elif [ "$ENV" == "QA" ]; then
+            # Deployment to QA
+            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
+            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
+            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
+          elif [ "$ENV" == "UAT" ]; then
+            # Deployment to UAT
+            Get-ChildItem -Path "D:\Achieve-ui-cicd" | Remove-Item -Recurse -Force
+            Copy-Item -Path "dist/achieve-ui/browser/*" -Destination "D:\Achieve-ui-cicd" -Recurse -Force
+            Copy-Item -Path "dist/achieve-ui/3rdpartylicenses.txt" -Destination "D:\Achieve-ui-cicd" -Force 
+          else
+            echo "Invalid environment"
+            exit 1
+          fi
